export const constants = {
  NUM: 0,
  BEGIN_TIME: 1,
  END_TIME: 2,
  DURATION: 3,
  OWNER: 4,
  NAME: 5,
  LOCATION: 6,
  LEADER: 7,
  MEMBER: 8,
  DETAILS: 9,
  PROCESS_FILE_NAME: "30-10-65-onsite.csv",
  ALLOW_PUSH_MESSAGE: true,
  PUSH_MESSAGE_TYPE: "flex",
};
